### PR TITLE
docs: added simpler option to run kitty with remote control

### PR DESCRIPTION
**Pull request by bhushan**
I spent whole day checking / debugging and reading code. I think it will help others to make things work better.

### CODE REVIEW

**Comment by knubie** [comment]
Thanks @bhushan! I agree this is a good addition to the docs. Would you mind also adding a link to this section in the FAQ for MacOS users? https://sw.kovidgoyal.net/kitty/faq/#how-do-i-specify-command-line-options-for-kitty-on-macos

**Comment by bhushan** [comment]
Yeah, Sure. I am going to update FAQ as well.

**Comment by bhushan** [comment]
@knubie could you please review it ?

**Comment by knubie** [comment]
Looks good, thanks @bhushan !

**Pull request merged**
