### PR TITLE
Allow for better isolation by allowing users to define the kittens installation path

### PR DESCRIPTION
**Pull request by hbarcelos**
The current suggested installation method has some drawbacks if you version control your Kitty configuration.

The plugin also assumes the kittens are installed in the same directory of `kitty.conf`, but this is a very strong assumption.

I usually install kittens as git submodules so they can be properly isolated and automatically upgraded when needed. For that to work, I cannot have the kittens in the same directory as `kitty.conf`, so I nest them into a directory.

The changes proposed here encompass 3 possible installation methods:
1. The git submodule: will add a submodule at `~/.config/kitty/vim-kitty-navigator/` and this location is automatically picked up by the Vim plugin.
2. The `~/.vim/plugged` direct reference: this is to avoid downloading the repo twice (one for `vim-plug`, other for the submodule).
    ```
    # kitty.conf
    map ctrl+j kitten ~/.vim/plugged/vim-kitty-navigator/pass_keys.py neighboring_window bottom ctrl+j
    ```
    ```
    " .vimrc
    let g:kitty_navigator_installation_path='~/.vim/plugged/vim-kitty-navigator'
    ```
3. The copy-pasta: keep the current installation method, only changing the default location to  `~/.config/kitty/vim-kitty-navigator/` to avoid requiring an additional configuration to work.

I'm not that well versed in either Vim Script or Vim help files, so please let me know if there are something that I can improve.

### CODE REVIEW

**Comment by knubie** [comment]
Hey @hbarcelos , sorry for the delay on this! I completely forgot about it. Feel free to ping me next time if I'm unresponsive. 

I think AFAICT the main issue here is that the location of `neighboring_window.py` is hardcoded in `plugin/kitty_navigator.vim`. For this plugin, I would like to keep the simplest installation method as the default (copying the python files to the kitty config directory), while also allowing users to use a more complex / custom installation path by setting the `g:kitty_navigator_installation_path` variable. To me that seems to strike the right balance between simplicity and flexibility.

**Comment by hbarcelos** [comment]
Hey @knubie did you have the chance to review this?

**Comment by hbarcelos** [comment]
@knubie I've sent you and e-mail regarding this PR a while ago. Any chance to get this reviewed?

**Comment by kintsugi** [comment]
Great minds think alike! I also wanted this functionality and didn't see this until after I finished implementing it and went to publish my PR 🤦🏼‍♂️

**Comment by primeapple** [comment]
I'm also interested in this! @knubie , any thoughts?

**Comment by knubie** [comment]
@primeapple I think this is solved by @kintsugi 's PR #33 (if I remember correctly). However I haven't merged it yet because it lacks documentation. I would be happy to merge that, or another PR branched from it with documentation added.

**Comment by hbarcelos** [comment]
Hey, sorry about the long delay.
What kind of documentation are you referring to?
This PR updates the README as well.

#33 did not fix the issues I was having with this TBH.

**Comment by knubie** [comment]
Hey @hbarcelos sorry for the confusion, I meant documentation for #33.

I think the reason I have no merged this PR yet is that I don't fully understand the problem it solves. I can try to assume the problem based on this line from the OP

> I usually install kittens as git submodules so they can be properly isolated and automatically upgraded when needed.

From that line I assume the problem to be wanting "properly isolating and automatically upgrading" the kittens associated with this plugin.

However, I'm still not sure what "properly isolated" means or why not doing that is a problem, or how they would be upgraded automatically with a git submodule (and what problem that solves in this case).

If you wanted to upgrade the kittens for this plugin, you would just upgrade the package from your vim configuration, which will automatically fetch the latest kittens and put them in the kitty config directory (assuming you have a post hook configuration step defined). So to me that solves the "automatically upgrading" problem.

#33 seems to solve the problems in a different way, by installing the kittens in the vim config directory and running them from there. In that way the kittens are "isolated" by not being in the kitty config directory with other config files, and the kittens are automatically managed by the plugin manager without needing to write a post install hook.

**Comment by hbarcelos** [comment]
Yeah, nevermind... Using the vim-plug hook in the README and adding those files to `.gitignore` in my kitty config has pretty much the same effect.

I'll close this PR.

Thanks a lot.

**Pull request closed without merging**
