### PR TITLE
Fixes #20

### LINKED ISSUE #20: Does not work with kitty 0.20.0+
See kitty commit:
https://github.com/kovidgoyal/kitty/commit/774a6c8c8bb1fbafd83bdcd598d64d7f7f1e2983#diff-f6baac98965e7e357c7dc7efe071c82de011ec8a14bf1f9fac7b6410326a3f2f

Key constants are removed. Thus an exception is raised in `pass_keys.py` for `getattr(fdt, 'GLFW_FKEY_{}'.format(key.upper()))`

It may seem like it works initially because if you raise an exception in `pass_keys.py` you can hop around vim -- for a bit. But you can still see that `pass_keys.py` raises an exception and functionality stops.

EDIT to add: love what this program promises, and thanks for creating. As I get capacity it's possible I can dive into this further.

### PR DESCRIPTION
**Pull request by sam-sjs**
Hey this should fix the issues caused after the recent kitty update detailed in Issue #20 .

I've created a kitty KeyEvent manually, my hope is that by interacting with Kitty at a bit of a higher level like this and relying on kitty to do all the encoding it will lessen the breaking changes due to kitty internal implementation changes in the future.

The new implementation caused a fair amount of code to become redundant which I have removed.

The navigator will no longer check for the "extended" keyboard profile as I do not believe it was actually using this functionality.  Please correct me if I am wrong or if you think this will cause any issues and I can make the necessary amendments.

### CODE REVIEW

**Comment by knubie** [comment]
Thanks @sam-sjs ! Would you be able to provide reproduction steps for the issue in #20? I just downloaded the latest version of kitty (0.23.1) and tried it out with the `master` branch `vim-kitty-navigator` and it seems to work fine. So I'd just like to know what's broken so I can compare `master` with this branch and verify that it fixes the issue.

**Comment by sam-sjs** [comment]
Hey @knubie.  Yeah no worries mate, I probably should have included them in the initial request so sorry about that.

Steps to reproduce:

1. Run the keyboard debugger with `kitty --debug-keyboard`
2. Open some kitty and vim splits in the window that opens
3. Whenever navigating within vim (or from vim to kitty) the debug output generates the following error:

```
KeyPress matched action: kitten
Traceback (most recent call last):
  File "lib/python3.9/kitty/boss.py", line 764, in dispatch_possible_special_key
  File "lib/python3.9/kitty/boss.py", line 851, in dispatch_action
  File "lib/python3.9/kitty/boss.py", line 1114, in kitten
  File "lib/python3.9/kitty/boss.py", line 1054, in _run_kitten
  File "lib/python3.9/kittens/tui/handler.py", line 154, in __call__
  File "/Users/sam/.config/kitty/pass_keys.py", line 66, in handle_result
    getattr(fdt, 'GLFW_FKEY_{}'.format(key.upper())),
AttributeError: module 'kitty.fast_data_types' has no attribute 'GLFW_FKEY_J'
sent key to child
```

I've just noticed now that you mention it that behaviour is still what we expect despite the error.  I suspect this is due to the `sent key to child` at the end of the error there.  Looks to me like kitty is recognising that the kitten failed and defaulting to sending the keypress to vim.

This PR therefore fixes the error as well as removing the code that is being bypassed anyway.

It actually clears up a bit of confusion I had haha, the `GLFW_FKEY` attributes haven't existed in `kitty.fast_data_types` since January.

Just want to say a quick thanks again for this plugin, it has really streamlined my OCD workflow haha!

**Comment by knubie** [comment]
Sorry for the delay, just got around to testing it out. Thanks for the contribution!

**Comment by aljets** [comment]
Nice work, thanks!!

**Comment by knubie** [comment]
@aljets What does your fzf config look like in vim? I assume you mean the `ctrl-j`/`ctrl/k` keys don't work to navigate fzf results? Those keys still work for me in fzf inside neovim.

**Comment by aljets** [comment]
@knubie `ctrl-j` populates the `fzf search field with `106;5u`. This is `ctrl-j` encoded, when I change `window.write_to_child(encoded)` to `window.write_to_child(key_mapping)` it populates `fzf` with `ctrl+j`. This also happens when running `fzf` directly in `kitty`. It happens when no configuration is applied to `fzf`.

**Comment by aljets** [comment]
I thought this might be related but if it works for you then I'm not sure. 
https://github.com/junegunn/fzf/issues/1980

**Pull request merged**
